name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: course.prafdin.ru
          username: chekulaev17
          port: 3179
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            set -e

            cd /home/chekulaev17/catty-reminders-app

            chmod +x deploy.sh

            echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u chekulaev17 --password-stdin

            ./deploy.sh \
              "ghcr.io/chekulaev17/catty-reminders-app" \
              "${{ github.sha }}"
